spring:
  datasource:
    url: jdbc:mysql://47.110.154.27:3306/demo?useUnicode=true&characterEncoding=UTF8
    username: toolalliance
    password: root123
  rabbitmq:
    host: test.pinheng.com
    username: admin
    password: root123
logging:
  level:
    com.lanxi.egift.merchant.web.mapper: debug
server:
  undertow:
    max-http-post-size: 0
    # 数量一般和cup核心一致
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载  io-threads*8
    worker-threads: 32
    direct-buffers: true




