fox:
  cloud:
    service:
      enableToken: true
      id: ${serviceId}
      type: core
      version: 1.0.0
spring:
  application:
    name: fox-cloud-plugin
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        health-check-path: ${server.servlet.context-path}/actuator/health
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialog: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
  datasource:
    url: jdbc:mysql://47.110.154.27:3306/demo?useUnicode=true&characterEncoding=UTF8
    username: toolalliance
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /${serviceId}
  port: ${port}


