spring:
  profiles:
    include: jpa
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialog: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://47.110.154.27:3306/demo?useUnicode=true&characterEncoding=UTF8
    username: toolalliance
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,log4j
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        reset-enable: false
        login-username: admin
        login-password: root123!@#
  rabbitmq:
    host: test.pinheng.com
    username: admin
    password: root123
management:
  endpoints:
    web:
      exposure:
        include: "info,health,bus-refresh"
server:
  undertow:
    max-http-post-size: 0
    # 数量一般和cup核心一致
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载  io-threads*8
    worker-threads: 32
    direct-buffers: true




