#通用配置信息
spring:
  profiles:
    include: jpa #是否加载jpa，可选jpa,feign
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialog: org.hibernate.dialect.MySQL5Dialect
server:
  undertow:
    max-http-post-size: 0
    # 数量一般和cup核心一致
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载  io-threads*8
    worker-threads: 32
    direct-buffers: true
management:
  endpoints:
    web:
      exposure:
        include: "info,health,bus-refresh"


